#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — deploy Cerebro to GreenNode Container Registry + Agent Runtime.
# Mirrors docs/deployment-greennode-agent-runtime.md.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE="deploy/deployment.env"   # gitignored — see .gitignore

banner "Deploy Cerebro to GreenNode"

# ── Stage 1: stage the DB and build the image ─────────────────────────────
stage "Build the image locally"
say "The demo database only exists on this machine, so the build happens here — never in CI."
ask DB_SOURCE_PATH "Path to workshop.duckdb on this machine:"
ask VERSION_TAG "Release version tag (e.g. v1.0.0):"
write_env DB_SOURCE_PATH "$DB_SOURCE_PATH"
write_env VERSION_TAG "$VERSION_TAG"

say "Staging the database into the build context..."
mkdir -p data
cp "$DB_SOURCE_PATH" data/workshop.duckdb
note "staged: data/workshop.duckdb ($(du -h data/workshop.duckdb | cut -f1))"

say "Building cerebro:${VERSION_TAG}..."
docker build \
  --build-arg BUILD_VERSION="$VERSION_TAG" \
  --build-arg BUILD_REVISION="$(git rev-parse --short HEAD)" \
  -t "cerebro:${VERSION_TAG}" .
note "✓ built cerebro:${VERSION_TAG}"

# ── Stage 2: verify locally before pushing anything ────────────────────────
stage "Verify the image locally"
say "Checking the baked-in database landed with the right owner/mode..."
docker run --rm --entrypoint /bin/sh "cerebro:${VERSION_TAG}" \
  -c 'stat -c "%u:%g %a %s" /data/workshop.duckdb'
note "expect: 10001:10001 444 <~75MB>"
confirm "Does that line look correct?" || warn "stop here and re-check the Dockerfile before continuing"

ask_secret CEREBRO_LLM_API_KEY "LLM API key (for this local smoke test only):"
ask CEREBRO_LLM_MODEL "LLM model name:"
write_env CEREBRO_LLM_MODEL "$CEREBRO_LLM_MODEL"

say "Starting a throwaway container on an ephemeral port (no /data mount — DB is baked in)..."
docker run --rm -d --name cerebro-verify \
  --publish 127.0.0.1::8000 \
  --env CEREBRO_LLM_API_KEY="$CEREBRO_LLM_API_KEY" \
  --env CEREBRO_LLM_MODEL="$CEREBRO_LLM_MODEL" \
  "cerebro:${VERSION_TAG}" >/dev/null
HOST_PORT=$(docker port cerebro-verify 8000/tcp | head -n1 | cut -d: -f2)
note "container listening on 127.0.0.1:${HOST_PORT}"
sleep 2
curl -sf "http://127.0.0.1:${HOST_PORT}/api/health/ready" | python3 -m json.tool || warn "readiness check failed — inspect with: docker logs cerebro-verify"
docker stop cerebro-verify >/dev/null
note "✓ stopped cerebro-verify"

if confirm "Run the full test suite and image-smoke script now (recommended)?"; then
  uv run --frozen --extra ai --extra dev python -m pytest -q
  scripts/deploy/image-smoke.sh "cerebro:${VERSION_TAG}"
  note "✓ pytest and image-smoke.sh passed"
else
  SKIPPED+=("pytest -q and scripts/deploy/image-smoke.sh cerebro:${VERSION_TAG}")
fi

# ── Stage 3: push to GreenNode Container Registry ──────────────────────────
stage "Push to GreenNode Container Registry"
REGISTRY_IMAGE="vcr.vngcloud.vn/111480-abp114537/cerebro:${VERSION_TAG}"
say "Target: ${REGISTRY_IMAGE}"
confirm "Are you already logged in (docker login vcr.vngcloud.vn)?" || {
  step "Run 'docker login vcr.vngcloud.vn' with your GreenNode registry credentials, then come back."
  pause "Press Enter once you're logged in"
}

docker tag "cerebro:${VERSION_TAG}" "$REGISTRY_IMAGE"
docker push "$REGISTRY_IMAGE"
note "✓ pushed ${REGISTRY_IMAGE}"

say "Confirming the image is pullable with the same credentials..."
docker pull "$REGISTRY_IMAGE" >/dev/null
note "✓ pull confirmed"
write_env REGISTRY_IMAGE "$REGISTRY_IMAGE"

# ── Stage 4: create the Agent Runtime app (console — you drive this) ───────
stage "Create the Agent Runtime app in the GreenNode console"
say "This part is entirely in the GreenNode console — open it yourself (I don't have its exact URL)."
say "Walk through the checklist in docs/deployment-greennode-agent-runtime.md §4 while you go."
step "Point the app at the image you just pushed: ${REGISTRY_IMAGE}"
pause "Press Enter once you're on the app-creation screen"

ask AR_PORT "Listening port the console expects (Enter if it's the default 8000):"
if [[ -n "$AR_PORT" && "$AR_PORT" != "8000" ]]; then
  warn "Console expects port ${AR_PORT}, but the Dockerfile CMD/HEALTHCHECK are hardcoded to 8000."
  warn "Stop and update the Dockerfile to use \${PORT:-8000} before deploying, then rebuild (stage 1)."
  SKIPPED+=("Dockerfile CMD/HEALTHCHECK port mismatch: console wants ${AR_PORT}, image is fixed to 8000")
fi

step "Set env vars from deploy/cerebro.env.example: CEREBRO_LLM_API_KEY, CEREBRO_LLM_MODEL, CEREBRO_LLM_BASE_URL."
if confirm "Also enabling the Basic Auth fallback (CEREBRO_BASIC_AUTH_USER/_PASSWORD)?"; then
  ask BASIC_AUTH_USER "Basic Auth username you set in the console:"
  write_env BASIC_AUTH_USER "$BASIC_AUTH_USER"
  note "remember the password you entered in the console — it isn't captured here."
fi

step "Point the health check at GET /api/health/ready."
step "Confirm whether persistent volumes exist (not needed — DB and bundle are baked in)."
step "Attach a custom domain / TLS if you want one."
step "Check whether Agent Runtime provides its own gateway/access-control auth."
pause "Press Enter once the app is created and deploying"

# ── Stage 5: verify the live deployment ─────────────────────────────────────
stage "Verify the live deployment"
ask AGENT_RUNTIME_URL "Live Agent Runtime URL (e.g. https://cerebro.something.greennode.app):"
write_env AGENT_RUNTIME_URL "$AGENT_RUNTIME_URL"

if [[ -n "${BASIC_AUTH_USER:-}" ]]; then
  ask_secret BASIC_AUTH_PASSWORD "Basic Auth password (to verify the live check):"
  say "Confirming unauthenticated requests are rejected..."
  unauth_status=$(curl -s -o /dev/null -w '%{http_code}' "${AGENT_RUNTIME_URL}/")
  [[ "$unauth_status" == "401" ]] && note "✓ unauthenticated request correctly returned 401" || warn "expected 401, got ${unauth_status}"
  curl -sf -u "${BASIC_AUTH_USER}:${BASIC_AUTH_PASSWORD}" "${AGENT_RUNTIME_URL}/api/health/ready" | python3 -m json.tool
else
  curl -sf "${AGENT_RUNTIME_URL}/api/health/ready" | python3 -m json.tool
fi
note "✓ live readiness check passed"

finish
